package sol.jara.franckie.validation.sample;

import sol.jara.franckie.validation.core.Attr;
import sol.jara.franckie.validation.core.CollectionValidator;
import sol.jara.franckie.validation.core.Command;
import sol.jara.franckie.validation.core.Rule;
import sol.jara.franckie.validation.core.Violation;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.function.Supplier;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Demonstrates capacity reservation validation for drops using context-based validation.
 *
 * A Capacity Reservation (CR) defines parachute capacity for a drop with:
 * - type: session, activity, or all-unit
 * - target_id: required for session/activity, null for all-unit
 * - parachute_type: type of parachute
 * - capacity: number of jumpers per parachute
 *
 * Constraint: Only one CR allowed per (type, target_id, parachute_type) per drop.
 *
 * This test demonstrates validation rule factories that accept external context,
 * keeping commands clean with only intent data.
 */
class CapacityReservationValidationTest {

    // ========== Test Models ==========

    /**
     * Represents a capacity reservation for a drop.
     */
    record CapacityReservation(
        String type,           // "session", "activity", or "all-unit"
        UUID targetId,         // Required for session/activity, null for all-unit
        String parachuteType,  // Type of parachute
        Integer capacity       // Number of jumpers
    ) {}

    /**
     * Represents a drop with capacity reservations.
     */
    record Drop(
        UUID dropId,
        List<CapacityReservation> capacityReservations
    ) {}

    /**
     * Command to add new capacity reservations to an existing drop.
     * Contains ONLY the user's intent - no context/existing data.
     */
    record AddCapacityReservationsCommand(
        UUID commandId,
        UUID dropId,
        List<CapacityReservation> newReservations
    ) implements Command {
        @Override
        public UUID getCommandId() {
            return commandId;
        }
    }

    // ========== Attribute Definitions ==========
    // In production, these would be generated by @ValidationProjection

    // CapacityReservation attributes
    static final Attr<CapacityReservation, String> TYPE =
        Attr.of("type", CapacityReservation::type);

    static final Attr<CapacityReservation, UUID> TARGET_ID =
        Attr.of("targetId", CapacityReservation::targetId);

    static final Attr<CapacityReservation, String> PARACHUTE_TYPE =
        Attr.of("parachuteType", CapacityReservation::parachuteType);

    static final Attr<CapacityReservation, Integer> CAPACITY =
        Attr.of("capacity", CapacityReservation::capacity);

    // Drop attributes
    static final Attr<Drop, UUID> DROP_ID =
        Attr.of("dropId", Drop::dropId);

    static final Attr<Drop, List<CapacityReservation>> CAPACITY_RESERVATIONS =
        Attr.of("capacityReservations", Drop::capacityReservations);

    // Command attributes
    static final Attr<AddCapacityReservationsCommand, UUID> COMMAND_ID =
        Attr.of("commandId", AddCapacityReservationsCommand::getCommandId);

    static final Attr<AddCapacityReservationsCommand, UUID> COMMAND_DROP_ID =
        Attr.of("dropId", AddCapacityReservationsCommand::dropId);

    static final Attr<AddCapacityReservationsCommand, List<CapacityReservation>> NEW_RESERVATIONS =
        Attr.of("newReservations", AddCapacityReservationsCommand::newReservations);

    // ========== Validation Rules ==========

    /**
     * Common rules for individual capacity reservations.
     */
    static class CapacityReservationRules {

        // Type must be one of the valid values
        public static final Rule<CapacityReservation> TYPE_VALID =
            TYPE.notNull()
                .and(TYPE.in("session", "activity", "all-unit"))
                .onInvalid("cr.type.invalid");

        // Parachute type must be present
        public static final Rule<CapacityReservation> PARACHUTE_TYPE_REQUIRED =
            PARACHUTE_TYPE.notNull()
                .onInvalid("cr.parachuteType.required");

        // Capacity must be positive
        public static final Rule<CapacityReservation> CAPACITY_POSITIVE =
            CAPACITY.notNull()
                .and(CAPACITY.gt(0))
                .onInvalid("cr.capacity.positive");

        // Target ID required when type is "session" or "activity"
        public static final Rule<CapacityReservation> TARGET_ID_REQUIRED_FOR_SESSION_OR_ACTIVITY =
            TYPE.eq("session")
                .or(TYPE.eq("activity"))
                .guard(TARGET_ID.notNull().onInvalid("cr.targetId.required"));

        // Target ID must be null when type is "all-unit"
        public static final Rule<CapacityReservation> TARGET_ID_NULL_FOR_ALL_UNIT =
            TYPE.eq("all-unit")
                .guard(TARGET_ID.isNull().onInvalid("cr.targetId.mustBeNull"));

        // Combine all basic rules
        public static Rule<CapacityReservation> all() {
            return TYPE_VALID
                .and(PARACHUTE_TYPE_REQUIRED)
                .and(CAPACITY_POSITIVE)
                .and(TARGET_ID_REQUIRED_FOR_SESSION_OR_ACTIVITY)
                .and(TARGET_ID_NULL_FOR_ALL_UNIT);
        }
    }

    /**
     * Validation rules for AddCapacityReservationsCommand.
     *
     * Uses TWO-PASS VALIDATION PATTERN:
     * - Pass 1: Validate each item in the collection individually (detailed violations)
     * - Pass 2: Validate command-level context (conflicts, authorization)
     *
     * This pattern provides:
     * - Detailed violations per item (e.g., "CR[0].type.invalid")
     * - Clean command objects (no embedded context)
     * - Reusable item-level rules
     * - Testable (inject different contexts)
     */
    static class AddCRRules {

        // Helper record for uniqueness checking
        record CRKey(String type, UUID targetId, String parachuteType) {}

        /**
         * Validates command structure and contextual concerns only.
         * Does NOT validate individual CRs.
         *
         * For complete validation, use validateTwoPass() helper or validate items separately.
         */
        public static Rule<AddCapacityReservationsCommand> contextOnly(
            Drop existingDrop,
            Supplier<List<UUID>> allowedActivityIdsSupplier
        ) {
            return basicValidation()
                .and(noConflictWithExisting(existingDrop))
                .and(activitiesAreAllowed(allowedActivityIdsSupplier));
        }

        /**
         * Complete two-pass validation helper.
         * Validates both individual CRs AND command context, collecting all violations.
         *
         * Usage:
         * <pre>
         * List&lt;Violation&gt; violations = AddCRRules.validateTwoPass(
         *     command,
         *     existingDrop,
         *     () -> activityService.getAllowedActivities(dropId)
         * );
         * CoreValidation.decideOn(violations);
         * </pre>
         */
        public static List<Violation> validateTwoPass(
            AddCapacityReservationsCommand command,
            Drop existingDrop,
            Supplier<List<UUID>> allowedActivityIdsSupplier
        ) {
            List<Violation> allViolations = new ArrayList<>();

            // Pass 1: Validate each CR individually using CollectionValidator
            allViolations.addAll(
                CollectionValidator.validateEach(
                    command.newReservations(),
                    CapacityReservationRules.all()
                )
            );

            // Pass 2: Validate command-level context
            allViolations.addAll(
                Rule.validate(
                    command,
                    contextOnly(existingDrop, allowedActivityIdsSupplier)
                )
            );

            return allViolations;
        }

        /**
         * Two-pass validation with early exit (fast-fail).
         * Stops after Pass 1 if any items are invalid.
         *
         * Use when you don't need all violations (e.g., for performance).
         */
        public static List<Violation> validateTwoPassFastFail(
            AddCapacityReservationsCommand command,
            Drop existingDrop,
            Supplier<List<UUID>> allowedActivityIdsSupplier
        ) {
            // Pass 1: Validate items
            List<Violation> itemViolations = CollectionValidator.validateEach(
                command.newReservations(),
                CapacityReservationRules.all()
            );

            // Early exit if items are invalid
            if (!itemViolations.isEmpty()) {
                return itemViolations;
            }

            // Pass 2: Only validate context if items are valid
            return Rule.validate(
                command,
                contextOnly(existingDrop, allowedActivityIdsSupplier)
            );
        }

        /**
         * Alias for contextOnly() for backwards compatibility.
         * Recommended: Use validateTwoPass() helper for complete validation.
         */
        public static Rule<AddCapacityReservationsCommand> all(
            Drop existingDrop,
            Supplier<List<UUID>> allowedActivityIdsSupplier
        ) {
            return contextOnly(existingDrop, allowedActivityIdsSupplier);
        }

        /**
         * Basic command-level validation.
         */
        private static Rule<AddCapacityReservationsCommand> basicValidation() {
            return COMMAND_ID.notNull().onInvalid("command.id.required")
                .and(COMMAND_DROP_ID.notNull().onInvalid("command.dropId.required"))
                .and(NEW_RESERVATIONS.notNull().onInvalid("command.newReservations.required"));
        }

        /**
         * No conflict with existing reservations on the drop.
         * Validates uniqueness of (type, targetId, parachuteType) across existing + new.
         */
        private static Rule<AddCapacityReservationsCommand> noConflictWithExisting(Drop existingDrop) {
            return NEW_RESERVATIONS.satisfies(
                newCRs -> {
                    if (newCRs == null) return true;

                    // Combine existing and new reservations
                    List<CapacityReservation> combined = new ArrayList<>();
                    if (existingDrop.capacityReservations() != null) {
                        combined.addAll(existingDrop.capacityReservations());
                    }
                    combined.addAll(newCRs);

                    // Check uniqueness
                    long uniqueCount = combined.stream()
                        .map(cr -> new CRKey(cr.type(), cr.targetId(), cr.parachuteType()))
                        .distinct()
                        .count();

                    return uniqueCount == combined.size();
                },
                "New reservations conflict with existing ones on the drop"
            ).onInvalid("command.reservations.conflict");
        }

        /**
         * All activities referenced in new reservations must be in the allowed list.
         * Uses supplier pattern for lazy/external data loading.
         */
        private static Rule<AddCapacityReservationsCommand> activitiesAreAllowed(
            Supplier<List<UUID>> allowedActivityIdsSupplier
        ) {
            return NEW_RESERVATIONS.satisfies(
                newCRs -> {
                    if (newCRs == null) return true;

                    // Get allowed activities (could be from DB, cache, etc.)
                    List<UUID> allowedIds = allowedActivityIdsSupplier.get();

                    // Check all activity-type reservations reference allowed activities
                    return newCRs.stream()
                        .filter(cr -> "activity".equals(cr.type()))
                        .map(CapacityReservation::targetId)
                        .allMatch(allowedIds::contains);
                },
                "Some activities are not allowed for this drop"
            ).onInvalid("command.activity.notAllowed");
        }

        /**
         * Validates that sessions are allowed for the drop.
         * Similar pattern to activities validation.
         */
        public static Rule<AddCapacityReservationsCommand> sessionsAreAllowed(
            Supplier<List<UUID>> allowedSessionIdsSupplier
        ) {
            return NEW_RESERVATIONS.satisfies(
                newCRs -> {
                    if (newCRs == null) return true;

                    List<UUID> allowedIds = allowedSessionIdsSupplier.get();

                    return newCRs.stream()
                        .filter(cr -> "session".equals(cr.type()))
                        .map(CapacityReservation::targetId)
                        .allMatch(allowedIds::contains);
                },
                "Some sessions are not allowed for this drop"
            ).onInvalid("command.session.notAllowed");
        }
    }

    // ========== Individual CR Validation Tests ==========

    @Test
    @DisplayName("given valid session CR when validate then no violations")
    void given__valid_session_cr__when__validate__then__no_violations() {
        // Given
        CapacityReservation cr = new CapacityReservation(
            "session",
            UUID.randomUUID(),
            "tandem",
            10
        );

        // When
        List<Violation> violations = Rule.validate(cr, CapacityReservationRules.all());

        // Then
        assertTrue(violations.isEmpty());
    }

    @Test
    @DisplayName("given valid activity CR when validate then no violations")
    void given__valid_activity_cr__when__validate__then__no_violations() {
        // Given
        CapacityReservation cr = new CapacityReservation(
            "activity",
            UUID.randomUUID(),
            "sport",
            5
        );

        // When
        List<Violation> violations = Rule.validate(cr, CapacityReservationRules.all());

        // Then
        assertTrue(violations.isEmpty());
    }

    @Test
    @DisplayName("given valid all-unit CR when validate then no violations")
    void given__valid_all_unit_cr__when__validate__then__no_violations() {
        // Given
        CapacityReservation cr = new CapacityReservation(
            "all-unit",
            null,  // No target ID for all-unit
            "student",
            15
        );

        // When
        List<Violation> violations = Rule.validate(cr, CapacityReservationRules.all());

        // Then
        assertTrue(violations.isEmpty());
    }

    @Test
    @DisplayName("given invalid type when validate then violation")
    void given__invalid_type__when__validate__then__violation() {
        // Given
        CapacityReservation cr = new CapacityReservation(
            "invalid-type",
            UUID.randomUUID(),
            "tandem",
            10
        );

        // When
        List<Violation> violations = Rule.validate(cr, CapacityReservationRules.all());

        // Then
        assertFalse(violations.isEmpty());
        assertTrue(violations.stream()
            .anyMatch(v -> v.translationKey().equals("cr.type.invalid")));
    }

    @Test
    @DisplayName("given missing target ID for session when validate then violation")
    void given__missing_target_id_for_session__when__validate__then__violation() {
        // Given
        CapacityReservation cr = new CapacityReservation(
            "session",
            null,  // Should have target ID for session
            "tandem",
            10
        );

        // When
        List<Violation> violations = Rule.validate(cr, CapacityReservationRules.all());

        // Then
        assertFalse(violations.isEmpty());
        assertTrue(violations.stream()
            .anyMatch(v -> v.translationKey().equals("cr.targetId.required")));
    }

    @Test
    @DisplayName("given missing target ID for activity when validate then violation")
    void given__missing_target_id_for_activity__when__validate__then__violation() {
        // Given
        CapacityReservation cr = new CapacityReservation(
            "activity",
            null,  // Should have target ID for activity
            "sport",
            5
        );

        // When
        List<Violation> violations = Rule.validate(cr, CapacityReservationRules.all());

        // Then
        assertFalse(violations.isEmpty());
        assertTrue(violations.stream()
            .anyMatch(v -> v.translationKey().equals("cr.targetId.required")));
    }

    @Test
    @DisplayName("given target ID present for all-unit when validate then violation")
    void given__target_id_present_for_all_unit__when__validate__then__violation() {
        // Given
        CapacityReservation cr = new CapacityReservation(
            "all-unit",
            UUID.randomUUID(),  // Should NOT have target ID for all-unit
            "student",
            15
        );

        // When
        List<Violation> violations = Rule.validate(cr, CapacityReservationRules.all());

        // Then
        assertFalse(violations.isEmpty());
        assertTrue(violations.stream()
            .anyMatch(v -> v.translationKey().equals("cr.targetId.mustBeNull")));
    }

    @Test
    @DisplayName("given zero capacity when validate then violation")
    void given__zero_capacity__when__validate__then__violation() {
        // Given
        CapacityReservation cr = new CapacityReservation(
            "session",
            UUID.randomUUID(),
            "tandem",
            0  // Capacity must be positive
        );

        // When
        List<Violation> violations = Rule.validate(cr, CapacityReservationRules.all());

        // Then
        assertFalse(violations.isEmpty());
        assertTrue(violations.stream()
            .anyMatch(v -> v.translationKey().equals("cr.capacity.positive")));
    }

    // ========== Command Validation Tests with Context ==========

    @Test
    @DisplayName("given valid command with no conflicts when validate then no violations")
    void given__valid_command_with_no_conflicts__when__validate__then__no_violations() {
        // Given - Existing drop with one reservation
        UUID sessionId = UUID.randomUUID();
        Drop existingDrop = new Drop(
            UUID.randomUUID(),
            List.of(
                new CapacityReservation("session", sessionId, "tandem", 10)
            )
        );

        // Command to add different reservations (no conflict)
        UUID activityId = UUID.randomUUID();
        AddCapacityReservationsCommand command = new AddCapacityReservationsCommand(
            UUID.randomUUID(),
            existingDrop.dropId(),
            List.of(
                new CapacityReservation("session", sessionId, "sport", 5),  // Same session, different parachute
                new CapacityReservation("activity", activityId, "tandem", 8)  // Different type
            )
        );

        // Context - allowed activities
        Supplier<List<UUID>> allowedActivities = () -> List.of(activityId);

        // When
        List<Violation> violations = Rule.validate(
            command,
            AddCRRules.all(existingDrop, allowedActivities)
        );

        // Then
        assertTrue(violations.isEmpty());
    }

    @Test
    @DisplayName("given command with conflicting reservation when validate then violation")
    void given__command_with_conflicting_reservation__when__validate__then__violation() {
        // Given - Existing drop with session + tandem reservation
        UUID sessionId = UUID.randomUUID();
        Drop existingDrop = new Drop(
            UUID.randomUUID(),
            List.of(
                new CapacityReservation("session", sessionId, "tandem", 10)
            )
        );

        // Command tries to add SAME combination (session + tandem)
        AddCapacityReservationsCommand command = new AddCapacityReservationsCommand(
            UUID.randomUUID(),
            existingDrop.dropId(),
            List.of(
                new CapacityReservation("session", sessionId, "tandem", 15)  // CONFLICT!
            )
        );

        // Context
        Supplier<List<UUID>> allowedActivities = () -> List.of();

        // When
        List<Violation> violations = Rule.validate(
            command,
            AddCRRules.all(existingDrop, allowedActivities)
        );

        // Then
        assertFalse(violations.isEmpty());
        assertTrue(violations.stream()
            .anyMatch(v -> v.translationKey().equals("command.reservations.conflict")));
    }

    @Test
    @DisplayName("given command with disallowed activity when validate then violation")
    void given__command_with_disallowed_activity__when__validate__then__violation() {
        // Given - Empty drop
        Drop existingDrop = new Drop(UUID.randomUUID(), List.of());

        // Command tries to add activity reservation
        UUID activityId = UUID.randomUUID();
        UUID otherActivityId = UUID.randomUUID();
        AddCapacityReservationsCommand command = new AddCapacityReservationsCommand(
            UUID.randomUUID(),
            existingDrop.dropId(),
            List.of(
                new CapacityReservation("activity", activityId, "tandem", 10)
            )
        );

        // Context - allowed activities does NOT include activityId
        Supplier<List<UUID>> allowedActivities = () -> List.of(otherActivityId);

        // When
        List<Violation> violations = Rule.validate(
            command,
            AddCRRules.all(existingDrop, allowedActivities)
        );

        // Then
        assertFalse(violations.isEmpty());
        assertTrue(violations.stream()
            .anyMatch(v -> v.translationKey().equals("command.activity.notAllowed")));
    }

    @Test
    @DisplayName("given command with allowed activity when validate then no violations")
    void given__command_with_allowed_activity__when__validate__then__no_violations() {
        // Given
        Drop existingDrop = new Drop(UUID.randomUUID(), List.of());

        UUID activityId = UUID.randomUUID();
        AddCapacityReservationsCommand command = new AddCapacityReservationsCommand(
            UUID.randomUUID(),
            existingDrop.dropId(),
            List.of(
                new CapacityReservation("activity", activityId, "tandem", 10)
            )
        );

        // Context - activity IS allowed
        Supplier<List<UUID>> allowedActivities = () -> List.of(activityId);

        // When
        List<Violation> violations = Rule.validate(
            command,
            AddCRRules.all(existingDrop, allowedActivities)
        );

        // Then
        assertTrue(violations.isEmpty());
    }

    @Test
    @DisplayName("given command with invalid CR using two-pass when validate then detailed violations")
    void given__command_with_invalid_cr_two_pass__when__validate__then__detailed_violations() {
        // Given
        Drop existingDrop = new Drop(UUID.randomUUID(), List.of());

        AddCapacityReservationsCommand command = new AddCapacityReservationsCommand(
            UUID.randomUUID(),
            existingDrop.dropId(),
            List.of(
                new CapacityReservation("invalid-type", UUID.randomUUID(), "tandem", 10),
                new CapacityReservation("session", null, "sport", 0)  // Missing target ID, zero capacity
            )
        );

        Supplier<List<UUID>> allowedActivities = () -> List.of();

        // When - using two-pass helper
        List<Violation> violations = AddCRRules.validateTwoPass(
            command,
            existingDrop,
            allowedActivities
        );

        // Then - we get DETAILED violations from each CR
        assertFalse(violations.isEmpty());
        assertTrue(violations.size() >= 3, "Should have multiple violations from both CRs");

        // First CR violations
        assertTrue(violations.stream()
            .anyMatch(v -> v.translationKey().equals("cr.type.invalid")));

        // Second CR violations
        assertTrue(violations.stream()
            .anyMatch(v -> v.translationKey().equals("cr.targetId.required")));
        assertTrue(violations.stream()
            .anyMatch(v -> v.translationKey().equals("cr.capacity.positive")));
    }

    @Test
    @DisplayName("given command with invalid CR using manual two-pass when validate then detailed violations")
    void given__command_with_invalid_cr_manual_two_pass__when__validate__then__detailed_violations() {
        // Given
        Drop existingDrop = new Drop(UUID.randomUUID(), List.of());

        AddCapacityReservationsCommand command = new AddCapacityReservationsCommand(
            UUID.randomUUID(),
            existingDrop.dropId(),
            List.of(
                new CapacityReservation("invalid-type", UUID.randomUUID(), "tandem", 10)
            )
        );

        Supplier<List<UUID>> allowedActivities = () -> List.of();

        // When - manual two-pass validation
        List<Violation> allViolations = new ArrayList<>();

        // Pass 1: Validate each CR individually
        for (CapacityReservation cr : command.newReservations()) {
            allViolations.addAll(Rule.validate(cr, CapacityReservationRules.all()));
        }

        // Pass 2: Validate command context (only if needed)
        if (allViolations.isEmpty()) {
            allViolations.addAll(Rule.validate(
                command,
                AddCRRules.all(existingDrop, allowedActivities)
            ));
        }

        // Then - we get detailed violations
        assertFalse(allViolations.isEmpty());
        assertTrue(allViolations.stream()
            .anyMatch(v -> v.translationKey().equals("cr.type.invalid")));
    }

    @Test
    @DisplayName("given empty drop with all-unit reservation when validate then no violations")
    void given__empty_drop_with_all_unit_reservation__when__validate__then__no_violations() {
        // Given
        Drop existingDrop = new Drop(UUID.randomUUID(), List.of());

        AddCapacityReservationsCommand command = new AddCapacityReservationsCommand(
            UUID.randomUUID(),
            existingDrop.dropId(),
            List.of(
                new CapacityReservation("all-unit", null, "student", 20)
            )
        );

        Supplier<List<UUID>> allowedActivities = () -> List.of();

        // When
        List<Violation> violations = Rule.validate(
            command,
            AddCRRules.all(existingDrop, allowedActivities)
        );

        // Then
        assertTrue(violations.isEmpty());
    }

    @Test
    @DisplayName("given conflicting all-unit reservation when validate then violation")
    void given__conflicting_all_unit_reservation__when__validate__then__violation() {
        // Given - Drop already has all-unit + student
        Drop existingDrop = new Drop(
            UUID.randomUUID(),
            List.of(
                new CapacityReservation("all-unit", null, "student", 20)
            )
        );

        // Command tries to add same all-unit + student
        AddCapacityReservationsCommand command = new AddCapacityReservationsCommand(
            UUID.randomUUID(),
            existingDrop.dropId(),
            List.of(
                new CapacityReservation("all-unit", null, "student", 25)  // CONFLICT!
            )
        );

        Supplier<List<UUID>> allowedActivities = () -> List.of();

        // When
        List<Violation> violations = Rule.validate(
            command,
            AddCRRules.all(existingDrop, allowedActivities)
        );

        // Then
        assertFalse(violations.isEmpty());
        assertTrue(violations.stream()
            .anyMatch(v -> v.translationKey().equals("command.reservations.conflict")));
    }

    @Test
    @DisplayName("given multiple new reservations with mix of valid and invalid when validate then violations")
    void given__multiple_new_reservations_with_mix__when__validate__then__violations() {
        // Given
        UUID sessionId = UUID.randomUUID();
        UUID allowedActivityId = UUID.randomUUID();
        UUID disallowedActivityId = UUID.randomUUID();

        Drop existingDrop = new Drop(
            UUID.randomUUID(),
            List.of(
                new CapacityReservation("session", sessionId, "tandem", 10)
            )
        );

        AddCapacityReservationsCommand command = new AddCapacityReservationsCommand(
            UUID.randomUUID(),
            existingDrop.dropId(),
            List.of(
                new CapacityReservation("session", sessionId, "sport", 5),  // Valid - different parachute
                new CapacityReservation("session", sessionId, "tandem", 12),  // Invalid - conflicts with existing
                new CapacityReservation("activity", allowedActivityId, "student", 8),  // Valid - allowed activity
                new CapacityReservation("activity", disallowedActivityId, "tandem", 6)  // Invalid - disallowed activity
            )
        );

        Supplier<List<UUID>> allowedActivities = () -> List.of(allowedActivityId);

        // When
        List<Violation> violations = Rule.validate(
            command,
            AddCRRules.all(existingDrop, allowedActivities)
        );

        // Then
        assertFalse(violations.isEmpty());
        // Should have conflict violation and activity not allowed violation
        assertTrue(violations.stream().anyMatch(v -> v.translationKey().equals("command.reservations.conflict")));
        assertTrue(violations.stream().anyMatch(v -> v.translationKey().equals("command.activity.notAllowed")));
    }

    @Test
    @DisplayName("given collection validator when validate list then all violations collected")
    void given__collection_validator__when__validate_list__then__all_violations_collected() {
        // Given - List with multiple invalid CRs
        List<CapacityReservation> crs = List.of(
            new CapacityReservation("invalid-type", UUID.randomUUID(), "tandem", 10),
            new CapacityReservation("session", null, "sport", 5),  // Missing target ID
            new CapacityReservation("all-unit", UUID.randomUUID(), "student", 0)  // Has target ID, zero capacity
        );

        // When - Using CollectionValidator utility
        List<Violation> violations = CollectionValidator.validateEach(
            crs,
            CapacityReservationRules.all()
        );

        // Then - All violations from all items collected
        assertFalse(violations.isEmpty());
        assertTrue(violations.size() >= 3, "Should have multiple violations from different CRs");

        // Verify specific violations
        assertTrue(violations.stream().anyMatch(v -> v.translationKey().equals("cr.type.invalid")));
        assertTrue(violations.stream().anyMatch(v -> v.translationKey().equals("cr.targetId.required")));
        assertTrue(violations.stream().anyMatch(v -> v.translationKey().equals("cr.targetId.mustBeNull")));
    }

    @Test
    @DisplayName("given collection validator with valid list when validate then no violations")
    void given__collection_validator_with_valid_list__when__validate__then__no_violations() {
        // Given
        List<CapacityReservation> crs = List.of(
            new CapacityReservation("session", UUID.randomUUID(), "tandem", 10),
            new CapacityReservation("activity", UUID.randomUUID(), "sport", 5),
            new CapacityReservation("all-unit", null, "student", 20)
        );

        // When
        List<Violation> violations = CollectionValidator.validateEach(
            crs,
            CapacityReservationRules.all()
        );

        // Then
        assertTrue(violations.isEmpty());
    }

    @Test
    @DisplayName("given lazy supplier when validate then supplier is called")
    void given__lazy_supplier__when__validate__then__supplier_is_called() {
        // Given - This test demonstrates lazy evaluation
        Drop existingDrop = new Drop(UUID.randomUUID(), List.of());

        UUID activityId = UUID.randomUUID();
        AddCapacityReservationsCommand command = new AddCapacityReservationsCommand(
            UUID.randomUUID(),
            existingDrop.dropId(),
            List.of(
                new CapacityReservation("activity", activityId, "tandem", 10)
            )
        );

        // Supplier that simulates DB fetch
        final boolean[] wasSupplierCalled = {false};
        Supplier<List<UUID>> allowedActivities = () -> {
            wasSupplierCalled[0] = true;
            return List.of(activityId);
        };

        // When
        List<Violation> violations = Rule.validate(
            command,
            AddCRRules.all(existingDrop, allowedActivities)
        );

        // Then
        assertTrue(violations.isEmpty());
        assertTrue(wasSupplierCalled[0], "Supplier should have been called during validation");
    }
}
